version: '3.9'
services:
  postgres:
    image: postgres:16
    container_name: mp-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "bochka"
      POSTGRES_DB: "market-place"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d market-place"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - feronova


volumes:
  pgdata:

networks:
  feronova:
    driver: bridge
