version: "3.9"

networks:
  dev: {}

services:
  frontend:
    build:
      context: ./affera
    ports:
      - "3000:3000"
    networks:
      - dev

  backend:
    build:
      context: ./backend
    environment:
      DATABASE_URL: postgresql://postgres:bochka@postgres:5432/affera?schema=public
      NODE_ENV: production
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: admin
      JWT_SECRET: your-jwt-secret
    depends_on:
      - postgres
    ports:
      - "4200:4200"
    networks:
      - dev

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bochka
      POSTGRES_DB: affera
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - dev

volumes:
  postgres_data:

